sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install libcgal-dev
  - sudo apt-get install libogre-1.9-dev
  - sudo apt-get install google-glog

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
