sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install libgoogle-glog-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libcgal-dev
  - sudo apt-get install libogre-1.9-dev
  - sudo apt-get install libois-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - smoothing/tests/representationsTest
