sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  # Get on latest gcc toolchain
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo apt-get install gcc-4.8 g++-4.8 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8;

  - sudo update-alternatives --config gcc

  - sudo apt-get install cmake
  - sudo apt-get install libgoogle-glog-dev
  - sudo apt-get install libgflags-dev

    # gtest install workaround on travis CI
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

    # install the latest version of cgal
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq libmpfr-dev
  - sudo apt-get install -qq libeigen3-dev
  - sudo apt-get install -qq libgmp3-dev
  - curl -L -o CGAL-4.9.tar.gz https://github.com/CGAL/cgal/archive/releases/CGAL-4.9.tar.gz
  - tar zxvf CGAL-4.9.tar.gz &> install.log
  - cd cgal-releases-CGAL-4.9
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_Eigen3=ON .
  - make
  - sudo make install &>> install.log
  - cd "${TRAVIS_BUILD_DIR}"

  - sudo apt-get install libcgal-dev
  - sudo apt-get install libogre-1.9-dev
  - sudo apt-get install libois-dev

    # install CEGUI
  - curl -L -o CEGUI.tar.bz2 "http://downloads.sourceforge.net/project/crayzedsgui/CEGUI%20Mk-2/0.8/cegui-0.8.7.tar.bz2?r=http%3A%2F%2Fcegui.org.uk%2Fdownload&ts=1477257533&use_mirror=pilotfiber"
  - tar xvf CEGUI.tar.bz2
  - (cd cegui-0.8.7; mkdir build; cd build; cmake -D CMAKE_BUILD_TYPE=Release ..; make; sudo make install; sudo ldconfig)

script:
  - ./build.sh
